// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptHostKey(arg1) {
  return window['go']['main']['App']['AcceptHostKey'](arg1);
}

export function ConnectSession(arg1) {
  return window['go']['main']['App']['ConnectSession'](arg1);
}

export function ConnectSessionExternal(arg1) {
  return window['go']['main']['App']['ConnectSessionExternal'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DisconnectTab(arg1) {
  return window['go']['main']['App']['DisconnectTab'](arg1);
}

export function DuplicateSession(arg1) {
  return window['go']['main']['App']['DuplicateSession'](arg1);
}

export function ExportSessions() {
  return window['go']['main']['App']['ExportSessions']();
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetAvailableTerminals() {
  return window['go']['main']['App']['GetAvailableTerminals']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessionTree() {
  return window['go']['main']['App']['GetSessionTree']();
}

export function ImportSessions() {
  return window['go']['main']['App']['ImportSessions']();
}

export function IsSSHSession(arg1) {
  return window['go']['main']['App']['IsSSHSession'](arg1);
}

export function MoveFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2);
}

export function MoveSession(arg1, arg2) {
  return window['go']['main']['App']['MoveSession'](arg1, arg2);
}

export function OpenLocalShell(arg1) {
  return window['go']['main']['App']['OpenLocalShell'](arg1);
}

export function QuickConnect(arg1) {
  return window['go']['main']['App']['QuickConnect'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['main']['App']['SaveFolder'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SelectPrivateKeyFile() {
  return window['go']['main']['App']['SelectPrivateKeyFile']();
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SftpDownloadFile(arg1, arg2) {
  return window['go']['main']['App']['SftpDownloadFile'](arg1, arg2);
}

export function SftpGetHome(arg1) {
  return window['go']['main']['App']['SftpGetHome'](arg1);
}

export function SftpGetPwd(arg1) {
  return window['go']['main']['App']['SftpGetPwd'](arg1);
}

export function SftpListDir(arg1, arg2) {
  return window['go']['main']['App']['SftpListDir'](arg1, arg2);
}

export function SftpUploadFile(arg1, arg2) {
  return window['go']['main']['App']['SftpUploadFile'](arg1, arg2);
}

export function ToggleFolderExpanded(arg1) {
  return window['go']['main']['App']['ToggleFolderExpanded'](arg1);
}
