// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {terminal} from '../models';
import {config} from '../models';
import {models} from '../models';

export function AcceptHostKey(arg1:boolean):Promise<void>;

export function ConnectSession(arg1:main.ConnectRequest):Promise<void>;

export function ConnectSessionExternal(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DuplicateSession(arg1:string):Promise<void>;

export function ExportSessions():Promise<string>;

export function ImportSessions():Promise<number>;

export function DisconnectTab(arg1:string):Promise<void>;

export function GetAvailableShells():Promise<Array<terminal.ShellInfo>>;

export function GetAvailableTerminals():Promise<Array<terminal.TerminalInfo>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetSession(arg1:string):Promise<models.Session>;

export function GetSessionTree():Promise<Array<models.TreeNode>>;

export function MoveFolder(arg1:string,arg2:string):Promise<void>;

export function MoveSession(arg1:string,arg2:string):Promise<void>;

export function OpenLocalShell(arg1:main.OpenShellRequest):Promise<void>;

export function QuickConnect(arg1:main.QuickConnectRequest):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SaveFolder(arg1:models.Folder):Promise<void>;

export function SaveSession(arg1:models.Session):Promise<void>;

export function SelectPrivateKeyFile():Promise<string>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function ToggleFolderExpanded(arg1:string):Promise<void>;
